import { FFCreator, FFScene, FFText } from "ffcreator";
import { DataBase } from "../audio.fetcher/type";
import * as path from "path";

export default class Generator{
    private targetPath:string;
    private resourcePath:string;
    private database:DataBase;
    private cache:string;
    private output:string;
    constructor(targetPath:string,resourcePath:string,database:DataBase,cacheDir:string,outputName:string){
        this.targetPath = targetPath;
        this.resourcePath = resourcePath;
        this.database = database;
        this.cache = cacheDir;
        this.output =outputName;
    }

    generate(){
        const creator = new FFCreator({
            width:1920,
            height:1080,
            outputDir:this.targetPath,
            cacheDir:this.cache,
            output:`${this.output}.mp4`
        });
        const prompt = new FFText({
            text:"[单词]",
            color:"#ffffff",
            x:0,
            y:0,
        });
        const copyright = new FFText({
            text:"Generated by Youdao_Pronouncer",
            color:"#ffffff",
            x:0,
            y:1900,
            fontSize:10
        });
        for(let i = 0;i<this.database.words.length;i++){
            /////Time One
            const scene1 = new FFScene();
            scene1.setBgColor("#000000");
            scene1.setDuration(3);
            const text1 = new FFText({
                text:this.database.words[i],
                x:1920/2,
                y:500,
                fontSize:50,
                color:"#ffffff"
            });
            text1.alignCenter();
            scene1.addChild(text1);
            scene1.addChild(prompt);
            scene1.addChild(copyright);
            scene1.addAudio({
                path:path.join(this.resourcePath,"words_" + (i + 1) + ".mp3"),
                volume:1
            });
            creator.addChild(scene1);

            /////Time Two
            const scene2 = new FFScene();
            scene2.setBgColor("#000000");
            scene2.setDuration(3);
            const text2 = new FFText({
                text:this.database.words[i],
                x:1920/2,
                y:500,
                fontSize:50,
                color:"#ffffff"
            });
            text2.alignCenter();
            scene2.addChild(text2);
            scene2.addChild(prompt);
            scene2.addChild(copyright);
            scene2.addAudio({
                path:path.join(this.resourcePath,"words_" + (i + 1) + ".mp3"),
                volume:1
            });
            creator.addChild(scene2);
        }

        for(let i = 0;i<this.database.trans.length;i++){
            /////Time One
            const scene1 = new FFScene();
            scene1.setBgColor("#000000");
            scene1.setDuration(3);
            const text1 = new FFText({
                text:this.database.trans[i],
                x:1920/2,
                y:500,
                fontSize:50,
                color:"#ffffff"
            });
            text1.alignCenter();
            scene1.addChild(text1);
            scene1.addChild(prompt);
            scene1.addChild(copyright);
            scene1.addAudio({
                path:path.join(this.resourcePath,"trans_" + (i + 1) + ".mp3"),
                volume:1
            });
            creator.addChild(scene1);

            /////Time Two
            const scene2 = new FFScene();
            scene2.setBgColor("#000000");
            scene2.setDuration(3);
            const text2 = new FFText({
                text:this.database.trans[i],
                x:1920/2,
                y:500,
                fontSize:50,
                color:"#ffffff"
            });
            text2.alignCenter();
            scene2.addChild(text2);
            scene2.addChild(prompt);
            scene2.addChild(copyright);
            scene2.addAudio({
                path:path.join(this.resourcePath,"trans_" + (i + 1) + ".mp3"),
                volume:1
            });
            creator.addChild(scene2);
        }

        for(let i = 0;i<this.database.phrases.length;i++){
            /////Time One
            const scene1 = new FFScene();
            scene1.setBgColor("#000000");
            scene1.setDuration(3);
            const text1 = new FFText({
                text:this.database.phrases[i],
                x:1920/2,
                y:500,
                fontSize:50,
                color:"#ffffff"
            });
            text1.alignCenter();
            scene1.addChild(text1);
            scene1.addChild(prompt);
            scene1.addChild(copyright);
            scene1.addAudio({
                path:path.join(this.resourcePath,"phrases_" + (i + 1) + ".mp3"),
                volume:1
            });
            creator.addChild(scene1);

            /////Time Two
            const scene2 = new FFScene();
            scene2.setBgColor("#000000");
            scene2.setDuration(3);
            const text2 = new FFText({
                text:this.database.phrases[i],
                x:1920/2,
                y:500,
                fontSize:50,
                color:"#ffffff"
            });
            text2.alignCenter();
            scene2.addChild(text2);
            scene2.addChild(prompt);
            scene2.addChild(copyright);
            scene2.addAudio({
                path:path.join(this.resourcePath,"phrases_" + (i + 1)+ ".mp3"),
                volume:1
            });
            creator.addChild(scene2);
        }
        creator.start();
        creator.on("start",()=>{
            console.log("Video Generator: Starting");
        });
        creator.on("error",(e)=>{
            throw e;
        });
        creator.on("complete",()=>{
            console.log("Video Generator: Generating Completed");
            process.exit();
        });
    }
}